# Generated by Django 5.2.15 on 2026-06-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Language', 'Language'), ('Framework', 'Framework'), ('Tool', 'Tool')], default='Language', max_length=20)),
            ],
        ),
    ]
